# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.261'  # Ruff version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/ambv/black
    rev: '21.5b1'
    hooks:
      - id: black
        language_version: python3.8
