---
# Project Information
site_name: Django URL Security
site_author: Matt Fisher
site_description: Django URL Security provides tests to ensure all the private endpoints in your Django project are private.

# Repository information
repo_name: Edrolo/django-url-security
repo_url: https://github.com/Edrolo/django-url-security
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Matt Fisher

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MattFisher
      name: MattFisher on GitHub

# Page tree
nav:
  - Home: index.md
